In [1]:
import glob
import numpy as np
from tqdm import tqdm

paths = glob.glob('/work/users/mi186veva/data_bea/raw_3d/*.npz')

quantities = []

for path in tqdm(paths):
    data = np.load(path)
    X, y = data['X'], data['y']
    quantities.append([X[y == 0].shape[0], X[y == 1].shape[0], X[y == 2].shape[0]])

    
quantities = np.array(quantities)
print(quantities)

summ = np.sum(quantities)

print(summ)

weights = summ / quantities

print(weights)

np.savez('weights', weights=weights, summ=summ, quantities=quantities)

for i, path in tqdm(enumerate(paths)):
    data = np.load(path)
    X, y = data['X'], data['y']
    weights_ = np.zeros(y.shape)
    
    for j in np.unique(y):
        weights_[y == j] = weights[i, j]
    
    data = {n: a for n, a in data.items()}
    data['weights'] = weights_
    
    np.savez(str(i), **data)
        
    


100%|██████████| 10/10 [00:23<00:00,  2.31s/it]
<ipython-input-1-b0a07743b844>:22: RuntimeWarning: divide by zero encountered in true_divide
  weights = summ / quantities
0it [00:00, ?it/s]

[[22885  9521 15524]
 [74271  2884     0]
 [ 8730   912  4545]
 [14401  3826 28302]
 [83599  1788 53220]
 [24915 26900 93658]
 [59706  1508 27101]
 [    0   400 44565]
 [12829  8711 14200]
 [67920  4964  5439]]
717224
[[  31.34035394   75.33074257   46.20097913]
 [   9.65685126  248.69070735           inf]
 [  82.15624284  786.42982456  157.80506051]
 [  49.80376363  187.46053319   25.3418133 ]
 [   8.57933707  401.13199105   13.47658775]
 [  28.78683524   26.66260223    7.65790429]
 [  12.01259505  475.6127321    26.4648537 ]
 [          inf 1793.06         16.09388534]
 [  55.90646192   82.33543795   50.50873239]
 [  10.5598351   144.48509267  131.8668873 ]]


4it [00:28,  7.00s/it]


KeyboardInterrupt: 

In [6]:
for i in range(10):
    data = np.load(str(i)+'.npz')

    for n, a in data.items():
        print(n, a.shape)
    
    print(np.unique(data['weights']))

X (47930, 5, 5, 81)
[ 6.45037286 16.13528512 18.45877351]
y (47930,)
[ 6.45037286 16.13528512 18.45877351]
indexes_in_datacube (47930, 2)
[ 6.45037286 16.13528512 18.45877351]
weights (47930,)
[ 6.45037286 16.13528512 18.45877351]
X (77155, 5, 5, 81)
[ 4.97173863 21.29472954]
y (77155,)
[ 4.97173863 21.29472954]
indexes_in_datacube (77155, 2)
[ 4.97173863 21.29472954]
weights (77155,)
[ 4.97173863 21.29472954]
X (14187, 5, 5, 81)
[42.29736541 63.04818482 67.33991228]
y (14187,)
[42.29736541 63.04818482 67.33991228]
indexes_in_datacube (14187, 2)
[42.29736541 63.04818482 67.33991228]
weights (14187,)
[42.29736541 63.04818482 67.33991228]
X (46529, 5, 5, 81)
[10.1248675  16.05175118 25.64099715]
y (46529,)
[10.1248675  16.05175118 25.64099715]
indexes_in_datacube (46529, 2)
[10.1248675  16.05175118 25.64099715]
weights (46529,)
[10.1248675  16.05175118 25.64099715]
X (138607, 5, 5, 81)
[ 4.41699063  5.3843292  34.34787472]
y (138607,)
[ 4.41699063  5.3843292  34.34787472]
indexes_in_data

In [2]:
f = {'a':'d', 'b':'d'}
f.keys()

dict_keys(['a', 'b'])

In [16]:
import glob
paths = glob.glob('/work/users/mi186veva/data_bea/raw_3d_weights/batch_sized/*.npz')

for path in paths[:1]:
    data = np.load(path)
    print(*data)
    
    print('weights' in data.keys())

X y PatientName PatientIndex indexes_in_datacube weights
True


In [4]:
f = ['g', 'a', 'd']
sorted(f)
print(f)
f = sorted(f)
print(f)

['g', 'a', 'd']
['a', 'd', 'g']


In [7]:
import pickle
import numpy as np

weights = pickle.load(open('/work/users/mi186veva/data_preprocessed/raw_3d_weighted/.weights', 'rb'))

print(weights['weights'])
print(weights['summ'])
print(weights['quantities'])

np.sum(weights['quantities'])
np.sum(weights['quantities'], axis=0)

[[   64.2922574    644.4094822    107.82412125]
 [           inf    64.4566835     67.90834868]
 [   51.33457181  1195.86051502   455.03892216]
 [  270.34492238            inf            inf]
 [   40.41938188   146.30375427   433.74894059]
 [   53.03302246  1107.16092715  1917.9499044 ]
 [  105.75740132            inf            inf]
 [   82.48263329  2126.08690123   695.91216872]
 [   43.17364357            inf            inf]
 [   48.96694166  2233.05387355   723.83302064]
 [   95.26180934  2697.92307692   410.63034223]
 [  384.20706297  8024.7024                inf]
 [   47.20502033            inf            inf]
 [   61.04626451   839.40401674   411.33757074]
 [   37.33392139  2186.32911944   594.66907754]
 [   74.9210373    930.68083132   439.06495667]
 [  250.32137153  5071.22244692  1592.20285714]
 [  249.87240933  2612.2078125   1671.2559147 ]
 [   70.32007908   289.32443034   115.91566516]
 [   53.8016005   1119.76758205   244.15534028]
 [   64.08360166  1191.88189163   742.47

array([4537769,  477670,  775718])