In [15]:
import pickle
import numpy as np

weights = pickle.load(open('/work/users/mi186veva/data_3d/svn_T_3x3/weights.weights', 'rb'))
#print(weights)


print('---------------------Weights---------------------')
print(weights['weights'])
print('---------------------Sum---------------------')
print(weights['sum'])
print('---------------------Quantities---------------------')
print(weights['quantities'])
print('---------------------Paths---------------------')
print(weights['paths'])

print('------------------------------------------------')
print('Calculated number of samples:', np.sum(weights['quantities']))
print('Calculated number of samples in classes:', np.sum(weights['quantities'], axis=0))

print('------------------------------------------------')
cumulative_weights = np.sum(weights['weights'], axis=0)
print('Cumulative weight over classes:', cumulative_weights)
print('Cumulative ratio', cumulative_weights[1] / cumulative_weights[0])


---------------------Weights---------------------
[[   89.26015768   285.89403181]
 [   50.70504681     0.        ]
 [  105.75740132     0.        ]
 [   32.35600098  1094.1184555 ]
 [  314.11279514 23436.63084112]
 [   44.73996004   351.78782353]
 [   38.11963883  1085.12310688]
 [   29.77670318 10470.64509395]
 [  376.16732918  2775.56115108]
 [   43.02623384   409.79156794]
 [   51.35612328   729.41230366]
 [   71.2410193    143.21232975]
 [   51.33457181  1195.86051502]
 [  149.22016602   352.10888795]
 [   25.77531953  2267.37748644]
 [   64.08360166  1191.88189163]
 [  176.04826424     0.        ]
 [   43.17364357     0.        ]
 [   44.17332218   777.46690436]
 [   61.04626451   839.40401674]
 [   41.36478651   357.68356868]
 [   82.13144794   204.39477545]
 [  270.34492238     0.        ]
 [   70.32007908   289.32443034]
 [   45.79682235  7519.3988006 ]
 [   36.45444502   491.18000196]
 [   48.96694166  2233.05387355]
 [  250.32137153  5071.22244692]
 [   53.8016005   1119.767

In [23]:
data = np.load(weights['paths'][0])
data_weights = data['weights']

unique = np.unique(data_weights)
print(unique)
#Check is unique weights are the same
assert np.all(unique == weights['weights'][0])

#check if the quantity of samples with some weight (respectively of the class with this weight) is the same to the quantity of samples of this class
assert np.flatnonzero(data_weights == unique[0]).shape[0] == weights['quantities'][0, 0]
assert np.flatnonzero(data_weights == unique[1]).shape[0] == weights['quantities'][0, 1]


[ 89.26015768 285.89403181]
(17543,)


<h1>Next section</h1>

In [1]:
import glob
import numpy as np
from tqdm import tqdm

paths = glob.glob('/work/users/mi186veva/data_bea/ColonData/raw_3d_weighted/*.npz')

quantities = []

for path in tqdm(paths):
    data = np.load(path)
    X, y = data['X'], data['y']
    quantities.append([X[y == 0].shape[0], X[y == 1].shape[0], X[y == 2].shape[0]])

    
quantities = np.array(quantities)
print(quantities)

summ = np.sum(quantities)

print(summ)

weights = summ / quantities

print(weights)

np.savez('weights', weights=weights, summ=summ, quantities=quantities)

for i, path in tqdm(enumerate(paths)):
    data = np.load(path)
    X, y = data['X'], data['y']
    weights_ = np.zeros(y.shape)
    
    for j in np.unique(y):
        weights_[y == j] = weights[i, j]
    
    data = {n: a for n, a in data.items()}
    data['weights'] = weights_
    
    np.savez(str(i), **data)
        
    


100%|██████████| 10/10 [00:23<00:00,  2.31s/it]
<ipython-input-1-b0a07743b844>:22: RuntimeWarning: divide by zero encountered in true_divide
  weights = summ / quantities
0it [00:00, ?it/s]

[[22885  9521 15524]
 [74271  2884     0]
 [ 8730   912  4545]
 [14401  3826 28302]
 [83599  1788 53220]
 [24915 26900 93658]
 [59706  1508 27101]
 [    0   400 44565]
 [12829  8711 14200]
 [67920  4964  5439]]
717224
[[  31.34035394   75.33074257   46.20097913]
 [   9.65685126  248.69070735           inf]
 [  82.15624284  786.42982456  157.80506051]
 [  49.80376363  187.46053319   25.3418133 ]
 [   8.57933707  401.13199105   13.47658775]
 [  28.78683524   26.66260223    7.65790429]
 [  12.01259505  475.6127321    26.4648537 ]
 [          inf 1793.06         16.09388534]
 [  55.90646192   82.33543795   50.50873239]
 [  10.5598351   144.48509267  131.8668873 ]]


4it [00:28,  7.00s/it]


KeyboardInterrupt: 

In [6]:
for i in range(10):
    data = np.load(str(i)+'.npz')

    for n, a in data.items():
        print(n, a.shape)
    
    print(np.unique(data['weights']))

X (47930, 5, 5, 81)
[ 6.45037286 16.13528512 18.45877351]
y (47930,)
[ 6.45037286 16.13528512 18.45877351]
indexes_in_datacube (47930, 2)
[ 6.45037286 16.13528512 18.45877351]
weights (47930,)
[ 6.45037286 16.13528512 18.45877351]
X (77155, 5, 5, 81)
[ 4.97173863 21.29472954]
y (77155,)
[ 4.97173863 21.29472954]
indexes_in_datacube (77155, 2)
[ 4.97173863 21.29472954]
weights (77155,)
[ 4.97173863 21.29472954]
X (14187, 5, 5, 81)
[42.29736541 63.04818482 67.33991228]
y (14187,)
[42.29736541 63.04818482 67.33991228]
indexes_in_datacube (14187, 2)
[42.29736541 63.04818482 67.33991228]
weights (14187,)
[42.29736541 63.04818482 67.33991228]
X (46529, 5, 5, 81)
[10.1248675  16.05175118 25.64099715]
y (46529,)
[10.1248675  16.05175118 25.64099715]
indexes_in_datacube (46529, 2)
[10.1248675  16.05175118 25.64099715]
weights (46529,)
[10.1248675  16.05175118 25.64099715]
X (138607, 5, 5, 81)
[ 4.41699063  5.3843292  34.34787472]
y (138607,)
[ 4.41699063  5.3843292  34.34787472]
indexes_in_data

In [2]:
f = {'a':'d', 'b':'d'}
f.keys()

dict_keys(['a', 'b'])

In [16]:
import glob
paths = glob.glob('/work/users/mi186veva/data_bea/raw_3d_weights/batch_sized/*.npz')

for path in paths[:1]:
    data = np.load(path)
    print(*data)
    
    print('weights' in data.keys())

X y PatientName PatientIndex indexes_in_datacube weights
True


In [4]:
f = ['g', 'a', 'd']
sorted(f)
print(f)
f = sorted(f)
print(f)

['g', 'a', 'd']
['a', 'd', 'g']


In [9]:
import glob

paths = glob.glob('/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/*.npz')

print(len(paths))
for path in paths:
    print(path)
    data = np.load(path)
    print(*data)
    print(np.unique(data['PatientName']), np.unique(data['PatientName']).shape)
    #print(data['P'].shape)

100
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled30.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled37.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled39.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled94.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled45.npz
X y PatientName PatientIndex ind

In [12]:
np.flatnonzero(np.core.defchararray.find('CP10', 'CP1') != -1)

array([0])