In [1]:
import glob
import numpy as np
from tqdm import tqdm

paths = glob.glob('/work/users/mi186veva/data_bea/ColonData/raw_3d_weighted/*.npz')

quantities = []

for path in tqdm(paths):
    data = np.load(path)
    X, y = data['X'], data['y']
    quantities.append([X[y == 0].shape[0], X[y == 1].shape[0], X[y == 2].shape[0]])

    
quantities = np.array(quantities)
print(quantities)

summ = np.sum(quantities)

print(summ)

weights = summ / quantities

print(weights)

np.savez('weights', weights=weights, summ=summ, quantities=quantities)

for i, path in tqdm(enumerate(paths)):
    data = np.load(path)
    X, y = data['X'], data['y']
    weights_ = np.zeros(y.shape)
    
    for j in np.unique(y):
        weights_[y == j] = weights[i, j]
    
    data = {n: a for n, a in data.items()}
    data['weights'] = weights_
    
    np.savez(str(i), **data)
        
    


100%|██████████| 10/10 [00:23<00:00,  2.31s/it]
<ipython-input-1-b0a07743b844>:22: RuntimeWarning: divide by zero encountered in true_divide
  weights = summ / quantities
0it [00:00, ?it/s]

[[22885  9521 15524]
 [74271  2884     0]
 [ 8730   912  4545]
 [14401  3826 28302]
 [83599  1788 53220]
 [24915 26900 93658]
 [59706  1508 27101]
 [    0   400 44565]
 [12829  8711 14200]
 [67920  4964  5439]]
717224
[[  31.34035394   75.33074257   46.20097913]
 [   9.65685126  248.69070735           inf]
 [  82.15624284  786.42982456  157.80506051]
 [  49.80376363  187.46053319   25.3418133 ]
 [   8.57933707  401.13199105   13.47658775]
 [  28.78683524   26.66260223    7.65790429]
 [  12.01259505  475.6127321    26.4648537 ]
 [          inf 1793.06         16.09388534]
 [  55.90646192   82.33543795   50.50873239]
 [  10.5598351   144.48509267  131.8668873 ]]


4it [00:28,  7.00s/it]


KeyboardInterrupt: 

In [6]:
for i in range(10):
    data = np.load(str(i)+'.npz')

    for n, a in data.items():
        print(n, a.shape)
    
    print(np.unique(data['weights']))

X (47930, 5, 5, 81)
[ 6.45037286 16.13528512 18.45877351]
y (47930,)
[ 6.45037286 16.13528512 18.45877351]
indexes_in_datacube (47930, 2)
[ 6.45037286 16.13528512 18.45877351]
weights (47930,)
[ 6.45037286 16.13528512 18.45877351]
X (77155, 5, 5, 81)
[ 4.97173863 21.29472954]
y (77155,)
[ 4.97173863 21.29472954]
indexes_in_datacube (77155, 2)
[ 4.97173863 21.29472954]
weights (77155,)
[ 4.97173863 21.29472954]
X (14187, 5, 5, 81)
[42.29736541 63.04818482 67.33991228]
y (14187,)
[42.29736541 63.04818482 67.33991228]
indexes_in_datacube (14187, 2)
[42.29736541 63.04818482 67.33991228]
weights (14187,)
[42.29736541 63.04818482 67.33991228]
X (46529, 5, 5, 81)
[10.1248675  16.05175118 25.64099715]
y (46529,)
[10.1248675  16.05175118 25.64099715]
indexes_in_datacube (46529, 2)
[10.1248675  16.05175118 25.64099715]
weights (46529,)
[10.1248675  16.05175118 25.64099715]
X (138607, 5, 5, 81)
[ 4.41699063  5.3843292  34.34787472]
y (138607,)
[ 4.41699063  5.3843292  34.34787472]
indexes_in_data

In [2]:
f = {'a':'d', 'b':'d'}
f.keys()

dict_keys(['a', 'b'])

In [16]:
import glob
paths = glob.glob('/work/users/mi186veva/data_bea/raw_3d_weights/batch_sized/*.npz')

for path in paths[:1]:
    data = np.load(path)
    print(*data)
    
    print('weights' in data.keys())

X y PatientName PatientIndex indexes_in_datacube weights
True


In [4]:
f = ['g', 'a', 'd']
sorted(f)
print(f)
f = sorted(f)
print(f)

['g', 'a', 'd']
['a', 'd', 'g']


In [3]:
import pickle
import numpy as np

weights = pickle.load(open('/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/.weights', 'rb'))

print(weights['weights'])
print(weights['summ'])
print(weights['quantities'])

np.sum(weights['quantities'])
np.sum(weights['quantities'], axis=0)

[[   6.57977764  115.48239491           inf]
 [  26.13341992           inf           inf]
 [  39.01661251  562.74754346           inf]
 [  11.67280738  390.61647429           inf]
 [   6.49176883   60.98582896           inf]
 [  18.70593704   24.4680886            inf]
 [  14.5931828   400.49220011           inf]
 [  47.09139785 3479.04205607           inf]
 [  38.94110571  390.00261917           inf]
 [   6.14336992   53.09620596           inf]
 [  42.86952266           inf           inf]
 [  11.37862787  141.22059939           inf]]
744515
[[113152   6447      0]
 [ 28489      0      0]
 [ 19082   1323      0]
 [ 63782   1906      0]
 [114686  12208      0]
 [ 39801  30428      0]
 [ 51018   1859      0]
 [ 15810    214      0]
 [ 19119   1909      0]
 [121190  14022      0]
 [ 17367      0      0]
 [ 65431   5272      0]]


array([668927,  75588,      0])

In [9]:
import glob

paths = glob.glob('/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/*.npz')

print(len(paths))
for path in paths:
    print(path)
    data = np.load(path)
    print(*data)
    print(np.unique(data['PatientName']), np.unique(data['PatientName']).shape)
    #print(data['P'].shape)

100
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled30.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled37.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled39.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled94.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled45.npz
X y PatientName PatientIndex ind

In [12]:
np.flatnonzero(np.core.defchararray.find('CP10', 'CP1') != -1)

array([0])