In [2]:
import pickle
import numpy as np

weights = pickle.load(open('C:\\Users\\tkachenko\\Desktop\\HSI\\colon\\svn_T_3x3\\weights.weights', 'rb'))
#weights = pickle.load(open('/work/users/mi186veva/data_3d/svn_T_3x3/weights.weights', 'rb'))
#print(weights)


print('---------------------Weights---------------------')
print(weights['weights'])
print('---------------------Sum---------------------')
print(weights['sum'])
print('---------------------Quantities---------------------')
print(weights['quantities'])
print('---------------------Paths---------------------')
print(weights['paths'])

print('------------------------------------------------')
print('Calculated number of samples:', np.sum(weights['quantities']))
print('Calculated number of samples in classes:', np.sum(weights['quantities'], axis=0))

print('------------------------------------------------')
cumulative_weights = np.sum(weights['weights'], axis=0)
print('Cumulative weight over classes:', cumulative_weights)
print('Cumulative ratio', cumulative_weights[1] / cumulative_weights[0])


---------------------Weights---------------------
[[2.47242483e+02 3.39902052e+03]
 [2.67626600e+02 0.00000000e+00]
 [2.36923252e+02 2.35674974e+03]
 [2.98326731e+02 2.09023879e+04]
 [7.01290449e+01 8.65707567e+02]
 [1.57387530e+02 0.00000000e+00]
 [1.14698095e+02 1.57105613e+02]
 [7.43300985e+01 2.37678587e+03]
 [4.36098995e+01 7.19844062e+02]
 [4.36401073e+02 7.44278037e+03]
 [5.73976159e+01 9.96904613e+02]
 [9.71486187e+01 0.00000000e+00]
 [4.02373975e+01 3.66618392e+02]
 [3.71237178e+01 3.22154195e+02]
 [9.45669436e+01 2.40748708e+03]
 [4.01330648e+01 4.28048900e+02]
 [2.76305578e+02 0.00000000e+00]
 [4.52240522e+02 4.52286249e+03]
 [6.72355063e+01 9.83101319e+02]
 [6.35168550e+01 5.87871074e+02]
 [3.58934297e+01 1.05772310e+03]
 [7.55516502e+01 1.89618949e+03]
 [7.54484288e+01 1.82598318e+02]
 [8.30167960e+01 2.69188843e+02]
 [7.85914506e+01 1.41913420e+03]
 [6.32063162e+01 1.00002482e+03]
 [6.47507455e+01 4.96295462e+02]
 [4.75964141e+01 6.50539703e+02]
 [8.63234976e+01 1.3103409

In [23]:
data = np.load(weights['paths'][0])
data_weights = data['weights']

unique = np.unique(data_weights)
print(unique)
#Check is unique weights are the same
assert np.all(unique == weights['weights'][0])

#check if the quantity of samples with some weight (respectively of the class with this weight) is the same to the quantity of samples of this class
assert np.flatnonzero(data_weights == unique[0]).shape[0] == weights['quantities'][0, 0]
assert np.flatnonzero(data_weights == unique[1]).shape[0] == weights['quantities'][0, 1]


[ 89.26015768 285.89403181]
(17543,)


<h1>Next section</h1>

In [1]:
import glob
import numpy as np
from tqdm import tqdm

paths = glob.glob('/work/users/mi186veva/data_bea/ColonData/raw_3d_weighted/*.npz')

quantities = []

for path in tqdm(paths):
    data = np.load(path)
    X, y = data['X'], data['y']
    quantities.append([X[y == 0].shape[0], X[y == 1].shape[0], X[y == 2].shape[0]])

    
quantities = np.array(quantities)
print(quantities)

summ = np.sum(quantities)

print(summ)

weights = summ / quantities

print(weights)

np.savez('weights', weights=weights, summ=summ, quantities=quantities)

for i, path in tqdm(enumerate(paths)):
    data = np.load(path)
    X, y = data['X'], data['y']
    weights_ = np.zeros(y.shape)
    
    for j in np.unique(y):
        weights_[y == j] = weights[i, j]
    
    data = {n: a for n, a in data.items()}
    data['weights'] = weights_
    
    np.savez(str(i), **data)
        
    


100%|██████████| 10/10 [00:23<00:00,  2.31s/it]
<ipython-input-1-b0a07743b844>:22: RuntimeWarning: divide by zero encountered in true_divide
  weights = summ / quantities
0it [00:00, ?it/s]

[[22885  9521 15524]
 [74271  2884     0]
 [ 8730   912  4545]
 [14401  3826 28302]
 [83599  1788 53220]
 [24915 26900 93658]
 [59706  1508 27101]
 [    0   400 44565]
 [12829  8711 14200]
 [67920  4964  5439]]
717224
[[  31.34035394   75.33074257   46.20097913]
 [   9.65685126  248.69070735           inf]
 [  82.15624284  786.42982456  157.80506051]
 [  49.80376363  187.46053319   25.3418133 ]
 [   8.57933707  401.13199105   13.47658775]
 [  28.78683524   26.66260223    7.65790429]
 [  12.01259505  475.6127321    26.4648537 ]
 [          inf 1793.06         16.09388534]
 [  55.90646192   82.33543795   50.50873239]
 [  10.5598351   144.48509267  131.8668873 ]]


4it [00:28,  7.00s/it]


KeyboardInterrupt: 

In [6]:
for i in range(10):
    data = np.load(str(i)+'.npz')

    for n, a in data.items():
        print(n, a.shape)
    
    print(np.unique(data['weights']))

X (47930, 5, 5, 81)
[ 6.45037286 16.13528512 18.45877351]
y (47930,)
[ 6.45037286 16.13528512 18.45877351]
indexes_in_datacube (47930, 2)
[ 6.45037286 16.13528512 18.45877351]
weights (47930,)
[ 6.45037286 16.13528512 18.45877351]
X (77155, 5, 5, 81)
[ 4.97173863 21.29472954]
y (77155,)
[ 4.97173863 21.29472954]
indexes_in_datacube (77155, 2)
[ 4.97173863 21.29472954]
weights (77155,)
[ 4.97173863 21.29472954]
X (14187, 5, 5, 81)
[42.29736541 63.04818482 67.33991228]
y (14187,)
[42.29736541 63.04818482 67.33991228]
indexes_in_datacube (14187, 2)
[42.29736541 63.04818482 67.33991228]
weights (14187,)
[42.29736541 63.04818482 67.33991228]
X (46529, 5, 5, 81)
[10.1248675  16.05175118 25.64099715]
y (46529,)
[10.1248675  16.05175118 25.64099715]
indexes_in_datacube (46529, 2)
[10.1248675  16.05175118 25.64099715]
weights (46529,)
[10.1248675  16.05175118 25.64099715]
X (138607, 5, 5, 81)
[ 4.41699063  5.3843292  34.34787472]
y (138607,)
[ 4.41699063  5.3843292  34.34787472]
indexes_in_data

In [2]:
f = {'a':'d', 'b':'d'}
f.keys()

dict_keys(['a', 'b'])

In [16]:
import glob
paths = glob.glob('/work/users/mi186veva/data_bea/raw_3d_weights/batch_sized/*.npz')

for path in paths[:1]:
    data = np.load(path)
    print(*data)
    
    print('weights' in data.keys())

X y PatientName PatientIndex indexes_in_datacube weights
True


In [4]:
f = ['g', 'a', 'd']
sorted(f)
print(f)
f = sorted(f)
print(f)

['g', 'a', 'd']
['a', 'd', 'g']


In [9]:
import glob

paths = glob.glob('/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/*.npz')

print(len(paths))
for path in paths:
    print(path)
    data = np.load(path)
    print(*data)
    print(np.unique(data['PatientName']), np.unique(data['PatientName']).shape)
    #print(data['P'].shape)

100
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled30.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled37.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled39.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled94.npz
X y PatientName PatientIndex indexes_in_datacube weights
['CP1' 'CP10' 'CP11' 'CP12' 'CP2' 'CP3' 'CP4' 'CP5' 'CP6' 'CP7' 'CP8'
 'CP9'] (12,)
/work/users/mi186veva/data_bea/ColonData/raw_3d_weights/shuffled/shuffled45.npz
X y PatientName PatientIndex ind

In [12]:
np.flatnonzero(np.core.defchararray.find('CP10', 'CP1') != -1)

array([0])