In [41]:
from tensorflow.random import set_seed
set_seed(3)
import random as python_random

from tensorflow.keras import backend as K

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

## GLOBAL SEED ##                                                   

x_train = tf.random.normal((10,1), 1, 1, dtype=tf.float32)
y_train = tf.math.sin(x_train)
x_test = tf.random.normal((10,1), 2, 3, dtype=tf.float32)
y_test = tf.math.sin(x_test)

print(x_train, y_train)



tf.Tensor(
[[ 0.17036277]
 [-0.82662714]
 [ 1.1251936 ]
 [ 2.1770082 ]
 [-0.1696676 ]
 [ 0.9906755 ]
 [ 2.7336211 ]
 [-0.03432238]
 [ 1.1381068 ]
 [ 0.08535814]], shape=(10, 1), dtype=float32) tf.Tensor(
[[ 0.16953988]
 [-0.73565096]
 [ 0.902351  ]
 [ 0.8218122 ]
 [-0.16885473]
 [ 0.83639646]
 [ 0.39674816]
 [-0.03431564]
 [ 0.90784127]
 [ 0.08525453]], shape=(10, 1), dtype=float32)


In [42]:


model = Sequential()
model.add(Dense(1200, input_shape=(1,), activation='relu'))  
model.add(Dense(150, activation='relu'))
model.add(Dense(80, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid')) 

loss="binary_crossentropy"
optimizer=tf.keras.optimizers.Adam(lr=0.0)
metrics=['mse']
epochs = 5
batch_size = 32
verbose = 1

model.compile(loss=loss,  
              optimizer=optimizer, 
              metrics=metrics) 
histpry = model.fit(x_train, y_train, epochs = epochs, batch_size=batch_size, verbose = verbose, shuffle=False)
predictions = model.predict(x_test)
print(predictions)



AttributeError: module 'tensorflow' has no attribute 'Session'

In [21]:
[[0.46148258]
 [0.4773212 ]
 [0.4582135 ]
 [0.47519344]
 [0.4972723 ]
 [0.4845588 ]
 [0.480704  ]
 [0.4883361 ]
 [0.4663327 ]
 [0.4953058 ]]

<>:1: SyntaxWarning: list indices must be integers or slices, not float; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not float; perhaps you missed a comma?
<ipython-input-21-ec81af900406>:1: SyntaxWarning: list indices must be integers or slices, not float; perhaps you missed a comma?
  [[0.50282514]
<ipython-input-21-ec81af900406>:1: SyntaxWarning: list indices must be integers or slices, not float; perhaps you missed a comma?
  [[0.50282514]
<ipython-input-21-ec81af900406>:1: SyntaxWarning: list indices must be integers or slices, not float; perhaps you missed a comma?
  [[0.50282514]
<ipython-input-21-ec81af900406>:1: SyntaxWarning: list indices must be integers or slices, not float; perhaps you missed a comma?
  [[0.50282514]
<ipython-input-21-ec81af900406>:1: SyntaxWarning: list indices must be integers or slices, not float; perhaps you missed a comma?
  [[0.50282514]
<ipython-input-21-ec81af900406>:1: SyntaxWarning: list indices must 

TypeError: list indices must be integers or slices, not float